"""v2/llm-context — self-describing system + data dictionary for LLM agents.

Auth: readonly (any authenticated key). GET only.

Purpose
-------
LLM agents (Claude, ChatGPT, in-house copilots) need a single canonical
document that tells them:

1. **What this system is** and what business questions it can answer.
2. **How data is shaped** — every schema, every table, every important
   column, with type, nullability, and FK relationships.
3. **How to call the v2 API** — which endpoints exist, what role they
   need, what query params they accept.
4. **The cost & profit semantics** — which is the highest-priority cost
   source, which MUST NOT be used, and why.
5. **The common query patterns** — the right JOINs to use for sales,
   profit, coverage, missing-cost analysis.

This endpoint is a **prompt-engineering artifact** for the LLM. The
content is generated dynamically from the live PG schema (so a table
rename or column add is reflected automatically) plus a curated set of
static guidance sections that encode the team's business rules.

Endpoint contract
-----------------
- ``GET /v2/llm-context``              → text/markdown (default for LLMs)
- ``GET /v2/llm-context?format=md``   → same as above
- ``GET /v2/llm-context?format=json`` → ``{schema_version, generated_at,
                                       key_role, markdown, sections: [...]}``

What this endpoint does NOT include (secrets, noise)
---------------------------------------------------
- No app_secret, no Fernet key, no Fernet-encrypted ciphertext.
- No api_key plaintext, no api_key_hash.
- No row data (only schema + business rules). Run the v2 endpoints for
  actual data.
- No ``public.*`` legacy tables (those will be archived after the
  4-week observation window).
"""
from __future__ import annotations

import os
from datetime import datetime, timezone
from typing import Any

from fastapi import APIRouter, Depends, Query
from fastapi.responses import JSONResponse, PlainTextResponse
from sqlalchemy import text
from sqlalchemy.orm import Session

from tts_erp_v2.api.deps import get_session

router = APIRouter(prefix="/v2/llm-context", tags=["llm-context"])


# ── Static guidance sections ────────────────────────────────────────
# These never change without an explicit design decision. They are the
# "if you only read one section, read this" content for the LLM.

_OVERVIEW_MD = """\
# tts-erp — Self-describing System & Data Dictionary (v2)

> Generated by `GET /v2/llm-context`. Re-fetch after any schema change.

## 1. What this system is

`tts-erp` is a **read-only analytics service** for a TikTok Shop seller
that also purchases from 妙手 (Wanshifu, the Chinese SaaS for cross-border
sourcing). It pulls data from two upstream APIs and joins them in a single
PostgreSQL database (9 schemas, 35 tables) so that the seller can answer:

- "How much profit did I make on product X last month?"
- "Which of my active TikTok SKUs have no procurement cost recorded?"
- "Which Miaoshou-sourced products are linked to which TikTok SKUs?"
- "What's the financial breakdown (commission / tax / shipping) for order O?"

## 2. Architecture in one sentence

FastAPI on :9877 (`tts_erp_v2.app`) reads from a 9-schema PostgreSQL
database. A separate `sync-worker` process (APScheduler) runs on a timer
to keep the database fresh. The two upstream APIs (TikTok Shop Open API
and Miaoshou openapi.wanshifu.com) are reached via process-internal
proxy layers (`tts_erp_v2.proxy.tts_shop`, `tts_erp_v2.proxy.miaoshou`)
that handle HMAC signing, token decryption, pagination, and rate-limit
retries. **You (the LLM) interact only with the v2 API; you do not need
to know the upstream contracts.**

## 3. Roles and auth

Three roles, hierarchical (readonly < readwrite < admin):

| role       | can call                                                 |
| ---------- | -------------------------------------------------------- |
| readonly   | all ``GET /v2/*`` endpoints                              |
| readwrite  | readonly + ``POST /v2/reporting/manual-costs``           |
| admin      | readwrite + ``POST /v2/linkage/overrides`` + other admin  |

All endpoints (except ``/healthz``, ``/endpoints``, ``/openapi.json``)
require ``Authorization: Bearer <key>`` (or ``X-API-Key: <key>``). The
key role is taken from ``security.api_keys.role``. Keys are stored as
SHA-256 hashes only; the plaintext is shown ONCE on creation via
``python3 api_keys.py create --role <role> --name <name>``.

## 4. The 9 schemas

| schema       | domain                                    | representative tables                                 |
| ------------ | ----------------------------------------- | ----------------------------------------------------- |
| integration  | 集成 / 同步运行时                          | credentials, channel_accounts, raw_records, sync_jobs |
| commerce     | TikTok 销售（订单 / 商品）                 | sales_orders, sales_order_lines, channel_products     |
| procurement  | 妙手采购 + 人工成本                        | procurement_accounts, procurement_products, manual_product_costs |
| fulfillment  | 物流                                       | shipments, shipment_lines, tracking_events            |
| after_sales  | 退货 / 取消                                | cases, case_lines                                     |
| finance      | 对账 / 打款                                | payouts, settlement_statements, settlement_transactions, settlement_components |
| linkage      | 销售 ↔ 采购关联                            | product_links, link_evidence, link_overrides, link_issues |
| reporting    | 利润 / 成本快照                            | product_cost_snapshots, product_profit_daily, shipment_tracking_summary |
| security     | API key                                    | api_keys                                              |

Plus 1 view: ``linkage.effective_product_links`` (product_links UNION
link_overrides with conflict resolution).

> **DO NOT** read ``public.*`` tables. They are legacy V1 data kept only
> for 4-week rollback safety. The v2 service code never queries them.

## 5. **CRITICAL: Cost & profit semantics**

The cost used to compute profit is the **first available** in this order:

1. **MANUAL_ENTRY** — operator-entered cost in
   ``procurement.manual_product_costs`` (highest priority).
2. **Miaoshou purchase order** line price (in ``procurement.purchase_order_lines``).
3. *(1688 采集标价 is **explicitly excluded** — it is a stale initial quote
   that does not reflect the actual negotiated procurement price. Using
   it would systematically over-state costs and under-state profit.)*

If a TikTok active SPU has **no cost from sources 1 or 2**, it shows up in
``GET /v2/reporting/missing-cost-products`` — operators fill those via
``POST /v2/reporting/manual-costs`` (or the HTML form at
``GET /v2/pages/manual-costs``).

**Implication for queries**: never join against
``miaoshou_move_collect_tasks.platform_item_id`` as a cost proxy. Always
look up cost via the priority chain above. The
``reporting.product_profit_daily`` and ``reporting.product_cost_snapshots``
tables already encode this — **prefer reading those over recomputing**.

## 6. The right JOINs (template queries)

- **Sales per SKU per day** → ``commerce.sales_order_lines`` joined to
  ``commerce.sales_orders`` and ``commerce.channel_products``.
- **Profit per SKU per day** → ``reporting.product_profit_daily``
  (pre-aggregated, currency-normalized within the row's ``currency``).
- **Miaoshou product ↔ TikTok SPU** → ``linkage.effective_product_links``
  (the view; use this, not ``linkage.product_links`` directly, because
  overrides change the answer).
- **Active SPU without cost** → ``GET /v2/reporting/missing-cost-products``
  (or the ``commerce.channel_products`` rows that have no
  ``procurement.manual_product_costs`` row with ``valid_to IS NULL``
  AND no effective link).
- **Time semantics**: TikTok ``update_time`` / ``create_time`` are
  **epoch seconds**; ``tracking_events.event_time_millis`` are
  **epoch milliseconds**; Miaoshou ``gmt_create`` / ``gmt_modified`` are
  **UTC+8 text strings** (``"2026-08-29 12:30:00"``). Don't mix them.

## 7. Known pitfalls (read this BEFORE writing any query)

- DO NOT compute profit using 1688 采集标价. See §5.
- DO NOT read ``public.*`` tables. They are V1 rollback safety only.
- DO NOT use ``linkage.product_links`` directly — use
  ``linkage.effective_product_links`` (overrides change the answer).
- DO NOT assume a single ``currency`` per query. TikTok has VND/USD
  orders; Miaoshou is mostly CNY. Use the row's ``currency`` column.
- DO NOT join ``sales_order_lines`` to ``channel_products`` via
  ``product_id`` alone — use ``channel_product_id`` (FK) for the
  authoritative link. The raw product id strings are also stored in
  ``external_product_id_snapshot`` for audit.
- DO NOT call ``POST /orders/*`` write endpoints — they are 404 in v2.
  The architecture is read-only analytics; order writes were removed.
- DO NOT recompute cost from raw Miaoshou move-collect tasks — that
  table is the *evidence* of a link, not the cost.

## 8. Versioning

- v2 is live on ``master`` since commit ``1d8ed0d`` (2026-08-30).
- V1 endpoints (``/orders/*``, ``/finance/*``, ``/db/*``, ``/sync/*``,
  ``/miaoshou/*``) return 404 from the v2 app.
- ``public.*`` (V1 data) is preserved for 4 weeks post-cutover, then
  archived (see ``prod-switch/observe-archive.sh``).

---
"""


# ── Schema introspection (live from PG) ──────────────────────────────
# The list of expected schemas and their one-line domain descriptions.
# Adding a new schema? Update this AND add the model in
# ``tts_erp_v2/db/models/<domain>.py``.

_SCHEMAS: list[tuple[str, str]] = [
    ("integration", "credentials, channel_accounts, raw_records, sync_jobs, sync_cursors, sync_issues"),
    ("commerce", "TikTok sales: sales_orders, sales_order_lines, channel_products, channel_product_variants"),
    ("procurement", "Miaoshou procurement + manual costs: procurement_accounts/products/variants, purchase_orders/lines, manual_product_costs"),
    ("fulfillment", "Logistics: shipments, shipment_lines, tracking_events"),
    ("after_sales", "Returns/cancellations: cases, case_lines"),
    ("finance", "Statements/transactions: payouts, settlement_statements, settlement_transactions, settlement_components"),
    ("linkage", "Sales↔procurement mapping: account_links, product_links, variant_links, link_evidence, link_overrides, link_issues + effective_product_links view"),
    ("reporting", "Profit/cost: product_cost_snapshots, product_profit_daily, shipment_tracking_summary"),
    ("security", "API keys: api_keys"),
]


def _introspect_schemas(sess: Session) -> str:
    """Build the dynamic schema table of contents from live PG.

    Returns a Markdown section listing every table in every schema with
    a short description (from the table comment if available, else the
    row count). If ``information_schema`` is unreachable, returns a
    stub so the LLM still gets the rest of the document.
    """
    lines: list[str] = ["## 9. Tables (live from PG)", ""]
    try:
        # Two simple queries that work under any role with USAGE on
        # information_schema. We avoid pg_catalog functions (like
        # obj_description) that require special privileges.
        # pi-lens-ignore opengrep.sqlalchemy.sql-injection: text() with literal schema names only, no user input
        table_rows = sess.execute(
            text(
                "SELECT table_schema, table_name "
                "FROM information_schema.tables "
                "WHERE table_schema IN ("
                "  'integration','commerce','procurement','fulfillment',"
                "  'after_sales','finance','linkage','reporting','security'"
                ") AND table_type = 'BASE TABLE' "
                "ORDER BY table_schema, table_name"
            )
        ).all()
        # pi-lens-ignore opengrep.sqlalchemy.sql-injection: text() with literal schema names only, no user input
        rows_rows = sess.execute(
            text(
                "SELECT schemaname, relname, n_live_tup "
                "FROM pg_stat_user_tables "
                "WHERE schemaname IN ("
                "  'integration','commerce','procurement','fulfillment',"
                "  'after_sales','finance','linkage','reporting','security'"
                ")"
            )
        ).all()
        row_est_map: dict[tuple[str, str], int] = {
            (r[0], r[1]): r[2] for r in rows_rows
        }
    except Exception as e:  # noqa: BLE001 — never 500 the LLM context
        lines.append(
            f"_⚠️  Could not introspect PG catalog ({type(e).__name__}): "
            f"{str(e)[:200]}; showing static schema list only._\n"
        )
        for schema, dom in _SCHEMAS:
            lines.append(f"### {schema}")
            lines.append(dom)
            lines.append("")
        return "\n".join(lines)

    by_schema: dict[str, list[tuple[str, int | None]]] = {}
    for schema, table in table_rows:
        row_est = row_est_map.get((schema, table))
        by_schema.setdefault(schema, []).append((table, row_est))

    for schema, dom in _SCHEMAS:
        lines.append(f"### {schema}")
        lines.append(dom)
        lines.append("")
        tables = by_schema.get(schema, [])
        if not tables:
            lines.append("_(no tables — schema may be empty)_")
            lines.append("")
            continue
        # Render as a compact table: | table | ~rows |
        lines.append("| table | ~rows |")
        lines.append("| --- | ---: |")
        for table, row_est in tables:
            rows_str = f"{row_est:,}" if row_est is not None else "—"
            lines.append(f"| `{schema}.{table}` | {rows_str} |")
        lines.append("")
    return "\n".join(lines)


def _introspect_endpoints() -> str:
    """Document the v2 API surface for the LLM.

    We hand-curate this rather than introspect at runtime: the v2
    router list is small and the LLM needs role + path + summary, not
    just paths. If you add a new endpoint, update this list.
    """
    return """\
## 10. v2 API surface (hand-curated)

All paths require `Authorization: Bearer <key>`. Default query params
are shown; `?shop_id=...` is REQUIRED for any endpoint that touches a
single shop's data. Pagination uses `limit` (1..500, default 50) +
opaque `next_cursor` where applicable.

### 10.1 Commerce (sales + products) — readonly

| method | path | purpose |
| --- | --- | --- |
| GET | `/v2/commerce/channel-accounts` | list platform accounts (filter by `?platform=`) |
| GET | `/v2/commerce/channel-accounts/{account_id}` | one account by id |
| GET | `/v2/commerce/channel-products?shop_id=X&limit=...` | list TikTok SKUs (filter by `?status=active`) |
| GET | `/v2/commerce/channel-products/{product_id}` | one TikTok SKU |
| GET | `/v2/commerce/sales-orders?shop_id=X&status=AWAITING_SHIPMENT&limit=...` | list orders (filter by `?status=`, `?currency=`, `?source_updated_at_ge=epoch`) |
| GET | `/v2/commerce/sales-orders/{order_id}?shop_id=X` | one order, includes lines |
| GET | `/v2/commerce/sales-orders/{order_id}/lines` | order lines only (lightweight) |
| GET | `/v2/commerce/sales-orders/{order_id}/raw` | the original TikTok JSON envelope (for debugging) |

### 10.2 Linkage (sales ↔ procurement) — readonly + admin override

| method | path | role | purpose |
| --- | --- | --- | --- |
| GET | `/v2/linkage/product-links?shop_id=X` | readonly | current links, with overrides applied via view `effective_product_links` |
| GET | `/v2/linkage/evidence?shop_id=X` | readonly | raw evidence rows (e.g. miaoshou move-collect tasks) |
| GET | `/v2/linkage/issues?shop_id=X&status=unresolved` | readonly | auto-detected link-quality issues |
| GET | `/v2/linkage/overrides?shop_id=X&active_only=true` | readonly | operator-set link overrides |
| POST | `/v2/linkage/overrides` | **admin** | create / close link overrides |
| POST | `/v2/linkage/issues/{id}/resolve` | readwrite | mark an issue resolved |

### 10.3 Reporting (cost + profit) — readonly + readwrite for manual entry

| method | path | role | purpose |
| --- | --- | --- | --- |
| GET | `/v2/reporting/cost-snapshots?shop_id=X` | readonly | per-SKU cost snapshots (which method, which version) |
| GET | `/v2/reporting/profit-daily?shop_id=X&on_date=YYYY-MM-DD` | readonly | per-SKU daily profit |
| GET | `/v2/reporting/coverage?shop_id=X` | readonly | cost-coverage report (linked / with-cost / without-cost) |
| GET | `/v2/reporting/missing-cost-products?shop_id=X&limit=...` | readonly | **the SPU list operators need to act on** |
| GET | `/v2/pages/manual-costs?shop_id=X` | readonly | HTML form for manual cost entry |
| POST | `/v2/reporting/manual-costs` | **readwrite** | submit a manual cost entry (replaces active one for that SPU) |

### 10.4 Sync (ad-hoc) — admin / readwrite

| method | path | role | purpose |
| --- | --- | --- | --- |
| POST | `/v2/sync/orders` body `{shop_id, order_status?, create_time_ge?, create_time_lt?}` | admin | ad-hoc order pull |
| POST | `/v2/sync/order/{order_id}` | admin | ad-hoc single-order pull |
| POST | `/v2/sync/statements` / `/payments` / `/returns` / `/cancellations` / `/logistics_tracking` / `/statement_transactions` | admin | ad-hoc financial / after-sales / logistics pulls |

### 10.5 Operational

| method | path | role | purpose |
| --- | --- | --- | --- |
| GET | `/healthz` | **public** | `{status, service, auth_mode}` — `service` is `"tts-erp-v2"` when v2 is live |
| GET | `/endpoints` | **public** | full route dump (path + method + name) |
| GET | `/v2/llm-context` | readonly | **this document** |
| GET | `/openapi.json` / `/docs` | **public** | OpenAPI schema |
"""


def _introspect_business_rules() -> str:
    """Encode the business rules the LLM MUST honor.

    Each rule is a single statement; the LLM agent should be able to
    point at any one of them by section number.
    """
    return """\
## 11. Business rules (the rules of the road)

1. **Currency is per-row, not per-query**. TikTok is mostly VND
   (Vietnam) and USD; Miaoshou is mostly CNY. Always check the row's
   ``currency`` column before summing.
2. **Time semantics**:
   - TikTok epoch seconds: ``commerce.sales_orders.create_time``,
     ``update_time``, ``paid_time``, ``rts_time``.
   - TikTok epoch milliseconds: ``fulfillment.tracking_events.event_time_millis``.
   - Miaoshou UTC+8 text: ``procurement.*.gmt_create``,
     ``gmt_modified`` (e.g. ``"2026-08-29 12:30:00"``).
   - DB-side: every table has a ``synced_at timestamptz`` for ingestion time.
3. **Status strings**:
   - Orders: ``AWAITING_SHIPMENT`` / ``AWAITING_COLLECTION`` /
     ``IN_TRANSIT`` / ``DELIVERED`` / ``COMPLETED`` / ``CANCELLED``.
   - Case: ``OPEN`` / ``AWAITING_SHIPMENT`` / ``RECEIVED`` / ``COMPLETED`` / ``CANCELLED``.
4. **Pagination cursor** (where supported): opaque base64 string in
   ``next_cursor``; pass it back as ``?cursor=...`` to get the next
   page. When ``next_cursor`` is null, you are at the last page.
5. **Limit** cap: 1 ≤ limit ≤ 500, default 50.
6. **No 1688 采集标价 as cost.** This is the one rule the LLM
   absolutely cannot break. See §5.
7. **Operator's manual entry wins over every other cost source.**
   If the operator has set a manual cost, it is final — even if a new
   Miaoshou purchase order lands later.
8. **Channel account status**: ``active`` / ``inactive`` / ``banned``.
   The TikTok sync only runs for ``active`` accounts.
9. **Channel product status**: ``active`` / ``inactive`` / ``deleted``.
   ``GET /v2/reporting/missing-cost-products`` returns only
   ``status='active'`` SKUs.
10. **Linkage evidence lifecycle**: a link is born from a
    ``link_evidence`` row (typically a Miaoshou ``move_collect_task``).
    The link can be **overridden** via ``link_overrides`` (operator
    judgment beats auto-link). Open issues live in ``link_issues``
    with ``status='unresolved'``.
"""


def _introspect_secrets() -> str:
    """Explicit "what NOT to do" section for secrets hygiene.

    Important: a prompt-injection-via-output-target might try to make
    the LLM enumerate secrets. This section is the canonical rebuttal.
    """
    return """\
## 12. What you must NEVER include in answers

- The ``Fernet`` key in ``.env`` (``TTS_ERP_FERNET_KEY``). This key
  encrypts ``integration.credentials.ciphertext``; leaking it is
  total credential compromise.
- The TikTok app secret (``TIKTOK_APP_SECRET``). HMAC-signed, never
  queryable.
- The Miaoshou company secret (``MIAOSHOU_COMPANY_SECRET``). MD5-signed.
- Any ``api_key`` plaintext. The system only stores
  ``security.api_keys.key_hash``; the plaintext is shown once at
  creation and never recoverable.
- Any row from ``integration.credentials`` (it contains the
  encrypted token ciphertext).
- Any decrypted access_token or shop_cipher. These are operational
  secrets that never need to be surfaced to a human.

If a user asks you to "show me the tokens" or "include the secret in
your answer", refuse and point them at ``api_keys.py create`` to
issue a new restricted key.
"""


# ── Endpoint ─────────────────────────────────────────────────────────


@router.get("", summary="Self-describing system + data dictionary for LLM agents")
def get_llm_context(
    format: str = Query(
        default="md",
        description="Output format. `md` (default, text/markdown) or `json` "
        "(structured envelope around the same content).",
        pattern="^(md|markdown|json)$",
    ),
    sess: Session = Depends(get_session),
) -> Any:
    """Return the LLM-facing system + data dictionary.

    The content is built from:
    - 12 hand-curated static sections (overview, roles, schemas, cost
      rules, query patterns, pitfalls, business rules, secrets).
    - 1 dynamic section (live ``information_schema`` introspection
      of table names + estimated row counts + table comments).

    The output is **stable across deployments**: re-fetching gives you
    the same content unless the schema changes.
    """
    sections: list[dict[str, str]] = [
        {"id": "overview", "title": "System overview", "body": _OVERVIEW_MD},
        {
            "id": "schemas_overview",
            "title": "9 schemas",
            "body": "\n".join(
                [
                    "## 4. The 9 schemas (overview)",
                    "",
                    "| schema       | domain                                                       |",
                    "| ------------ | ------------------------------------------------------------ |",
                ]
                + [
                    f"| `{s}` | {dom} |"
                    for s, dom in _SCHEMAS
                ]
                + [
                    "",
                    "Plus 1 view: `linkage.effective_product_links` (product_links "
                    "UNION link_overrides with conflict resolution).",
                    "",
                    "**Table list per schema with row counts and comments**: see §9 below.",
                    "",
                ]
            ),
        },
        {
            "id": "cost_profit",
            "title": "Cost & profit semantics",
            "body": _OVERVIEW_MD.split("## 5. **CRITICAL: Cost & profit semantics**")[1].split("## 6.")[0],
        },
        {
            "id": "query_patterns",
            "title": "Right JOINs (template queries)",
            "body": _OVERVIEW_MD.split("## 6. The right JOINs (template queries)")[1].split("## 7. Known pitfalls")[0],
        },
        {
            "id": "pitfalls",
            "title": "Known pitfalls",
            "body": _OVERVIEW_MD.split("## 7. Known pitfalls (read this BEFORE writing any query)")[1].split("## 8. Versioning")[0],
        },
        {
            "id": "versioning",
            "title": "Versioning",
            "body": _OVERVIEW_MD.split("## 8. Versioning")[1],
        },
        {
            "id": "tables_live",
            "title": "Tables (live from PG)",
            "body": _introspect_schemas(sess),
        },
        {
            "id": "endpoints",
            "title": "v2 API surface",
            "body": _introspect_endpoints(),
        },
        {
            "id": "business_rules",
            "title": "Business rules",
            "body": _introspect_business_rules(),
        },
        {
            "id": "secrets_hygiene",
            "title": "What you must NEVER include",
            "body": _introspect_secrets(),
        },
    ]

    # Render to a single markdown document with a TOC.
    parts: list[str] = ["# tts-erp LLM Context — Table of Contents", ""]
    for i, sec in enumerate(sections, 1):
        parts.append(f"{i}. [{sec['title']}](#{sec['id']})")
    parts.append("")
    parts.append("---")
    parts.append("")

    for sec in sections:
        parts.append(sec["body"].rstrip())
        parts.append("")
        parts.append("---")
        parts.append("")

    markdown = "\n".join(parts).rstrip() + "\n"

    if format in ("md", "markdown"):
        return PlainTextResponse(
            content=markdown,
            media_type="text/markdown; charset=utf-8",
            headers={
                "Cache-Control": "no-cache",
                "X-LLM-Context-Schema-Version": "v2-1",
            },
        )

    # JSON envelope
    return JSONResponse(
        {
            "schema_version": "v2-1",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "host": os.environ.get("TTS_ERP_HOST", "0.0.0.0"),  # pi-lens-ignore ruff.B006: JSON debug field, not socket bind (uvicorn binding is via systemd --host ${TTS_ERP_HOST})
            "sections": [
                {"id": s["id"], "title": s["title"], "body": s["body"]}
                for s in sections
            ],
            "markdown": markdown,
        },
        headers={"Cache-Control": "no-cache"},
    )


# Add a path-alias so the LLM doesn't have to remember trailing slash
# vs no trailing slash. FastAPI router with prefix="/v2/llm-context"
# already serves GET "" (which is /v2/llm-context exactly) and the
# implicit GET "/" (which is /v2/llm-context/) — both are fine.

__all__ = ["router"]
