-- =============================================================================
-- oauth_receiver schema (regenerated by scripts/regen_schema.py)
-- =============================================================================
--
-- DO NOT EDIT BY HAND. Run `python3 scripts/regen_schema.py` after any
-- schema change; it rewrites schema_oauth.sql + schema_tts_erp.sql.
--
-- To apply:
--     docker exec -i postgres psql -U postgres -d oauth_receiver < schema_oauth.sql
--
-- Idempotency notes: see schema_tts_erp.sql header (same rules).
-- =============================================================================

-- PostgreSQL database dump



SELECT pg_catalog.set_config('search_path', '', false);

-- Name: touch_updated_at(); Type: FUNCTION; Schema: public; Owner: -

CREATE OR REPLACE FUNCTION public.touch_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;



-- Name: oauth_tokens; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.oauth_tokens (
    id bigint NOT NULL,
    shop_id text NOT NULL,
    provider text DEFAULT 'tiktok'::text NOT NULL,
    access_token_encrypted bytea NOT NULL,
    refresh_token_encrypted bytea NOT NULL,
    shop_cipher_encrypted bytea,
    shop_name text,
    shop_region text,
    seller_type text,
    access_token_expires_at bigint,
    refresh_token_expires_at bigint,
    granted_scopes text[],
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    last_used_at timestamp with time zone,
    last_refresh_at timestamp with time zone
);








-- Name: oauth_tokens id; Type: DEFAULT; Schema: public; Owner: -



-- Name: oauth_tokens oauth_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.oauth_tokens
    ADD CONSTRAINT oauth_tokens_pkey PRIMARY KEY (id);


-- Name: oauth_tokens oauth_tokens_shop_provider_unique; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.oauth_tokens
    ADD CONSTRAINT oauth_tokens_shop_provider_unique UNIQUE (shop_id, provider);


-- Name: idx_oauth_tokens_expires; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_oauth_tokens_expires ON public.oauth_tokens USING btree (access_token_expires_at);


-- Name: oauth_tokens trg_oauth_tokens_touch; Type: TRIGGER; Schema: public; Owner: -

CREATE OR REPLACE TRIGGER trg_oauth_tokens_touch BEFORE UPDATE ON public.oauth_tokens FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();


-- PostgreSQL database dump complete

\unrestrict 8pUlFzGfV5XejPbvLvKWLzBnb23YTUmsSJ5U1WHaRluzWY1B73Q9rfo7ZrE9rYc

