-- =============================================================================
-- tts_erp schema (regenerated by scripts/regen_schema.py)
-- =============================================================================
--
-- DO NOT EDIT BY HAND. Run `python3 scripts/regen_schema.py` after any
-- schema change; it rewrites schema_oauth.sql + schema_tts_erp.sql.
--
-- To apply:
--     docker exec -i postgres psql -U postgres -d tts_erp < schema_tts_erp.sql
--
-- FK policy (2026-08-27): sync-mirror tables carry NO foreign keys.
-- Writes are idempotent upserts keyed by natural primary keys; parents
-- are always written before children by the sync layer. The one legacy
-- exception (logistics_events → orders) was dropped in Wave 2 together
-- with that dead table.
--
-- Idempotency:
--   - CREATE TABLE / CREATE INDEX / CREATE TRIGGER use IF NOT EXISTS /
--     OR REPLACE — re-applying is safe.
--   - ALTER TABLE ... ADD CONSTRAINT is NOT idempotent in PG 18; on a
--     populated DB a re-apply emits "already exists" notices (harmless).
--
-- Designed target is "fresh DB clean apply". Do not re-run against a
-- populated production DB without reading the diff carefully.
-- =============================================================================

-- PostgreSQL database dump



SELECT pg_catalog.set_config('search_path', '', false);

-- Name: cleanup_sync_log(integer); Type: FUNCTION; Schema: public; Owner: -

CREATE OR REPLACE FUNCTION public.cleanup_sync_log(retention_days integer DEFAULT 60) RETURNS TABLE(deleted_count bigint, cutoff_timestamp timestamp with time zone)
    LANGUAGE plpgsql
    AS $$
DECLARE
    cutoff TIMESTAMPTZ;
    rows_deleted BIGINT;
BEGIN
    cutoff := now() - (retention_days || ' days')::INTERVAL;

    DELETE FROM sync_log
    WHERE COALESCE(finished_at, started_at) < cutoff;

    GET DIAGNOSTICS rows_deleted = ROW_COUNT;

    RETURN QUERY SELECT rows_deleted, cutoff;
END;
$$;


-- Name: touch_updated_at(); Type: FUNCTION; Schema: public; Owner: -

CREATE OR REPLACE FUNCTION public.touch_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;


-- Name: trg_sync_log_retention_fn(); Type: FUNCTION; Schema: public; Owner: -

CREATE OR REPLACE FUNCTION public.trg_sync_log_retention_fn() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    PERFORM cleanup_sync_log(60);
    RETURN NULL;  -- AFTER STATEMENT trigger ignores the return value
END;
$$;



-- Name: analytics_audit_log; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.analytics_audit_log (
    id bigint NOT NULL,
    request_id text,
    endpoint text NOT NULL,
    method text NOT NULL,
    path text NOT NULL,
    status integer NOT NULL,
    key_prefix text,
    records_in integer,
    records_ok integer,
    records_rej integer,
    error_code text,
    error_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 2026-08-31: error_message column backfill for existing deploys.
ALTER TABLE public.analytics_audit_log
    ADD COLUMN IF NOT EXISTS error_message text;








-- Name: analytics_cursors; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.analytics_cursors (
    seller_id text NOT NULL,
    advertiser_id text NOT NULL,
    storage_key text NOT NULL,
    campaign_id text NOT NULL,
    latest_completed_day date,
    last_updated_at timestamp with time zone DEFAULT now() NOT NULL,
    request_id text,
    first_seen_day date,
    CONSTRAINT ck_analytics_cursors_storage CHECK ((storage_key = ANY (ARRAY['productAnalyses'::text, 'sessionAnalyses'::text, 'campaignChangeLogs'::text])))
);


-- Name: analytics_daily_completeness; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.analytics_daily_completeness (
    seller_id text NOT NULL,
    advertiser_id text NOT NULL,
    storage_key text NOT NULL,
    campaign_id text NOT NULL,
    day date NOT NULL,
    expected_page_count integer NOT NULL,
    is_complete boolean DEFAULT false NOT NULL,
    completed_at timestamp with time zone,
    last_recomputed_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_analytics_daily_completeness_expected CHECK ((expected_page_count > 0)),
    CONSTRAINT ck_analytics_daily_completeness_storage CHECK ((storage_key = ANY (ARRAY['productAnalyses'::text, 'sessionAnalyses'::text, 'campaignChangeLogs'::text])))
);


-- Name: analytics_daily_pages; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.analytics_daily_pages (
    seller_id text NOT NULL,
    advertiser_id text NOT NULL,
    storage_key text NOT NULL,
    campaign_id text NOT NULL,
    day date NOT NULL,
    page integer NOT NULL,
    inserted_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_analytics_daily_pages_page CHECK ((page > 0)),
    CONSTRAINT ck_analytics_daily_pages_storage CHECK ((storage_key = ANY (ARRAY['productAnalyses'::text, 'sessionAnalyses'::text, 'campaignChangeLogs'::text])))
);


-- Name: analytics_records; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.analytics_records (
    id bigint NOT NULL,
    idempotency_key text NOT NULL,
    source_record_id text,
    seller_id text NOT NULL,
    advertiser_id text NOT NULL,
    storage_key text NOT NULL,
    campaign_id text NOT NULL,
    day date NOT NULL,
    page integer NOT NULL,
    shop_name text,
    endpoint text NOT NULL,
    method text NOT NULL,
    request_body jsonb,
    response_data jsonb NOT NULL,
    source text NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    schema_version integer DEFAULT 1 NOT NULL,
    protocol_version integer DEFAULT 1 NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    request_id text,
    expected_page_count integer,
    CONSTRAINT ck_analytics_records_page CHECK ((page > 0)),
    CONSTRAINT ck_analytics_records_protocol CHECK ((protocol_version > 0)),
    CONSTRAINT ck_analytics_records_schema CHECK ((schema_version > 0)),
    CONSTRAINT ck_analytics_records_storage CHECK ((storage_key = ANY (ARRAY['productAnalyses'::text, 'sessionAnalyses'::text, 'campaignChangeLogs'::text])))
);








-- Name: analytics_shop_timezones; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.analytics_shop_timezones (
    seller_id text NOT NULL,
    advertiser_id text NOT NULL,
    timezone text DEFAULT 'Asia/Shanghai'::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


-- Name: api_keys; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.api_keys (
    id bigint NOT NULL,
    key_hash text NOT NULL,
    key_prefix text NOT NULL,
    name text NOT NULL,
    role text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_used_at timestamp with time zone,
    expires_at timestamp with time zone,
    scopes text[] DEFAULT ARRAY[]::text[] NOT NULL,
    CONSTRAINT api_keys_role_check CHECK ((role = ANY (ARRAY['readonly'::text, 'readwrite'::text, 'admin'::text])))
);








-- Name: cancellations; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.cancellations (
    cancel_id text NOT NULL,
    shop_id text,
    order_id text,
    cancel_status text,
    cancel_reason text,
    cancel_reason_text text,
    cancel_type text,
    role text,
    should_replenish_stock boolean,
    create_time bigint,
    update_time bigint,
    raw jsonb NOT NULL,
    synced_at timestamp with time zone DEFAULT now() NOT NULL
);


-- Name: logistics_sync_targets; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.logistics_sync_targets (
    order_id text NOT NULL,
    shop_id text NOT NULL,
    last_synced_at timestamp with time zone,
    last_n_events integer,
    needs_resync boolean DEFAULT true NOT NULL
);


-- Name: logistics_tracking; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.logistics_tracking (
    order_id text NOT NULL,
    shop_id text,
    tracking_number text,
    n_events integer DEFAULT 0 NOT NULL,
    first_event_at bigint,
    last_event_at bigint,
    last_action_code integer,
    last_description text,
    final_status text,
    arrived_overseas boolean DEFAULT false NOT NULL,
    arrived_at bigint,
    origin_departed_at bigint,
    import_cleared_at bigint,
    delivered_at bigint,
    returned_at bigint,
    raw jsonb NOT NULL,
    synced_at timestamp with time zone DEFAULT now() NOT NULL
);


-- Name: logistics_tracking_events; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.logistics_tracking_events (
    order_id text NOT NULL,
    action_code integer NOT NULL,
    event_time bigint NOT NULL,
    description text,
    location text,
    synced_at timestamp with time zone DEFAULT now() NOT NULL
);


-- Name: miaoshou_collect_box_details; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.miaoshou_collect_box_details (
    platform text NOT NULL,
    common_collect_box_detail_id bigint CONSTRAINT miaoshou_collect_box_detail_common_collect_box_detail__not_null NOT NULL,
    app_account_id bigint,
    sub_app_account_id bigint,
    item_num text,
    title text,
    thumbnail text,
    list_thumbnail text,
    price numeric,
    min_sku_price numeric,
    max_sku_price numeric,
    stock integer,
    remark text,
    status text,
    reason text,
    gmt_create text,
    gmt_modified text,
    weight numeric,
    max_sku_weight numeric,
    min_sku_weight numeric,
    common_collect_box_group_id bigint,
    common_collect_box_group_name text,
    owner_sub_account_alias_name text,
    is_mark text,
    is_cb integer,
    is_cnsc integer,
    raw_json jsonb,
    synced_at timestamp with time zone DEFAULT now()
);


-- Name: miaoshou_move_collect_tasks; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.miaoshou_move_collect_tasks (
    platform text NOT NULL,
    move_collect_task_detail_id text CONSTRAINT miaoshou_move_collect_tasks_move_collect_task_detail_i_not_null NOT NULL,
    collect_box_detail_id text,
    shop_id text,
    item_num text,
    cid text,
    source text,
    source_site text,
    source_item_id text,
    title text,
    thumbnail text,
    is_timing text,
    status text,
    reason text,
    gmt_create text,
    gmt_modified text,
    platform_item_id text,
    is_renew_item boolean,
    shop_name text,
    site_name text,
    site text,
    source_item_url text,
    item_edit_url text,
    breadcrumb text,
    owner_sub_app_account_id bigint,
    owner_sub_account_alias_name text,
    raw_json jsonb,
    synced_at timestamp with time zone DEFAULT now()
);


-- Name: miaoshou_price_templates; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.miaoshou_price_templates (
    price_template_id bigint NOT NULL,
    app_account_id bigint,
    sub_app_account_id bigint,
    platform text,
    site text,
    name text,
    remark text,
    currency text,
    display_weight_unit text,
    profit_type text,
    profit_percent numeric,
    fixed_profit_amount numeric,
    exchange_rate numeric,
    discount numeric,
    price_tail_compute_type text,
    price_tail text,
    price_process_decimal_type text,
    logistics_compute_type text,
    weight_ref_type text,
    first_weight_charge numeric,
    first_weight_interval numeric,
    continued_weight_charge numeric,
    continued_weight_interval numeric,
    logistics_charge numeric,
    platform_charge_percent numeric,
    payment_charge_percent numeric,
    activity_charge_percent numeric,
    withdraw_charge_percent numeric,
    other_charge numeric,
    is_cal_light_cargo integer,
    light_cargo_coefficient integer,
    weight_logistics_charge_list text,
    domestic_logistics_compute_type text,
    domestic_logistics_first_weight_charge numeric,
    domestic_logistics_first_weight_interval numeric,
    domestic_logistics_continued_weight_charge numeric,
    domestic_logistics_continued_weight_interval numeric,
    domestic_logistics_charge numeric,
    buyer_logistic_charge numeric,
    seller_logistic_charge numeric,
    has_seller_logistic_charge integer,
    official_tpl_mode text,
    official_tpl_logistics_channel text,
    snapshot_id bigint,
    gmt_create text,
    gmt_modified text,
    raw_json jsonb,
    synced_at timestamp with time zone DEFAULT now()
);


-- Name: miaoshou_shops; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.miaoshou_shops (
    shop_id bigint NOT NULL,
    platform text NOT NULL,
    site text NOT NULL,
    platform_shop_name text,
    shop_nick text,
    parent_shop_id bigint,
    is_cb integer,
    is_cnsc integer,
    status text,
    gmt_expire text,
    gmt_last_auth text,
    raw_json jsonb,
    synced_at timestamp with time zone DEFAULT now()
);


-- Name: order_items; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.order_items (
    order_id text NOT NULL,
    item_id text NOT NULL,
    shop_id text,
    sku_id text,
    product_id text,
    product_name text,
    sku_name text,
    sku_image text,
    quantity integer,
    sku_price numeric(18,2),
    raw jsonb NOT NULL
);


-- Name: order_shippings; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.order_shippings (
    order_id text NOT NULL,
    shop_id text,
    tracking_number text,
    shipping_provider_id text,
    shipping_provider_name text,
    raw jsonb NOT NULL,
    synced_at timestamp with time zone DEFAULT now() NOT NULL
);


-- Name: orders; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.orders (
    order_id text NOT NULL,
    shop_id text NOT NULL,
    order_status_name text,
    payment_amount numeric(18,2),
    payment_currency text,
    total_amount numeric(18,2),
    buyer_email text,
    buyer_message text,
    create_time bigint,
    update_time bigint,
    paid_time bigint,
    shipped_time bigint,
    delivered_time bigint,
    cancelled_time bigint,
    fulfillment_type text,
    raw jsonb NOT NULL,
    synced_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


-- Name: payments; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.payments (
    payment_id text NOT NULL,
    shop_id text,
    status text,
    currency text,
    amount_value numeric(18,2),
    settlement_amount_value numeric(18,2),
    payment_amount_before_value numeric(18,2),
    reserve_amount_value numeric(18,2),
    exchange_rate text,
    bank_account text,
    create_time bigint,
    paid_time bigint,
    raw jsonb NOT NULL,
    synced_at timestamp with time zone DEFAULT now() NOT NULL
);


-- Name: returns; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.returns (
    return_id text NOT NULL,
    shop_id text,
    order_id text,
    return_status text,
    return_reason text,
    return_type text,
    role text,
    create_time bigint,
    update_time bigint,
    raw jsonb NOT NULL,
    synced_at timestamp with time zone DEFAULT now() NOT NULL
);


-- Name: shops; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.shops (
    shop_id text NOT NULL,
    shop_name text,
    shop_region text,
    seller_type text,
    last_seen_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


-- Name: statement_transactions; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.statement_transactions (
    txn_id text NOT NULL,
    statement_id text NOT NULL,
    shop_id text,
    order_id text,
    order_create_time bigint,
    type text,
    currency text,
    actual_return_shipping_fee_amount numeric(18,2),
    actual_shipping_fee_amount numeric(18,2),
    adjustment_amount numeric(18,2),
    affiliate_ads_commission_amount numeric(18,2),
    affiliate_commission_amount numeric(18,2),
    affiliate_commission_before_pit numeric(18,2),
    affiliate_partner_commission_amount numeric(18,2),
    after_seller_discounts_subtotal_amount numeric(18,2),
    customer_order_refund_amount numeric(18,2),
    customer_paid_shipping_fee_amount numeric(18,2),
    customer_paid_shipping_fee_refund_amount numeric(18,2),
    customer_payment_amount numeric(18,2),
    customer_refund_amount numeric(18,2),
    customer_shipping_fee_amount numeric(18,2),
    customer_shipping_fee_offset_amount numeric(18,2),
    fbm_shipping_cost_amount numeric(18,2),
    fbt_fulfillment_fee_amount numeric(18,2),
    fbt_fulfillment_fee_reimbursement_amount numeric(18,2),
    fbt_shipping_cost_amount numeric(18,2),
    fee_amount numeric(18,2),
    gross_sales_amount numeric(18,2),
    gross_sales_refund_amount numeric(18,2),
    isr_income_tax_amount numeric(18,2),
    iva_vat_amount numeric(18,2),
    net_sales_amount numeric(18,2),
    pit_amount numeric(18,2),
    platform_commission_amount numeric(18,2),
    platform_discount_amount numeric(18,2),
    platform_discount_refund_amount numeric(18,2),
    platform_refund_subsidy_amount numeric(18,2),
    platform_shipping_fee_discount_amount numeric(18,2),
    promo_shipping_incentive_amount numeric(18,2),
    referral_fee_amount numeric(18,2),
    refund_administration_fee_amount numeric(18,2),
    refund_shipping_cost_discount_amount numeric(18,2),
    retail_delivery_fee_amount numeric(18,2),
    retail_delivery_fee_payment_amount numeric(18,2),
    retail_delivery_fee_refund_amount numeric(18,2),
    return_shipping_fee_amount numeric(18,2),
    revenue_amount numeric(18,2),
    sales_tax_amount numeric(18,2),
    sales_tax_payment_amount numeric(18,2),
    sales_tax_refund_amount numeric(18,2),
    seller_discount_amount numeric(18,2),
    seller_discount_refund_amount numeric(18,2),
    settlement_amount numeric(18,2),
    shipping_cost_amount numeric(18,2),
    shipping_cost_discount_amount numeric(18,2),
    shipping_fee_amount numeric(18,2),
    shipping_fee_subsidy_amount numeric(18,2),
    shipping_insurance_fee_amount numeric(18,2),
    signature_confirmation_fee_amount numeric(18,2),
    transaction_fee_amount numeric(18,2),
    raw jsonb NOT NULL,
    synced_at timestamp with time zone DEFAULT now() NOT NULL
);


-- Name: statements; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.statements (
    statement_id text NOT NULL,
    shop_id text,
    payment_id text,
    currency text,
    payment_status text,
    statement_time bigint,
    payment_time bigint,
    revenue_amount numeric(18,2),
    fee_amount numeric(18,2),
    net_sales_amount numeric(18,2),
    shipping_cost_amount numeric(18,2),
    adjustment_amount numeric(18,2),
    settlement_amount numeric(18,2),
    raw jsonb NOT NULL,
    synced_at timestamp with time zone DEFAULT now() NOT NULL
);


-- Name: sync_log; Type: TABLE; Schema: public; Owner: -

CREATE TABLE IF NOT EXISTS public.sync_log (
    id bigint NOT NULL,
    shop_id text,
    sync_type text,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    rows_affected integer,
    status text,
    error_message text
);








-- Name: analytics_audit_log id; Type: DEFAULT; Schema: public; Owner: -



-- Name: analytics_records id; Type: DEFAULT; Schema: public; Owner: -



-- Name: api_keys id; Type: DEFAULT; Schema: public; Owner: -



-- Name: sync_log id; Type: DEFAULT; Schema: public; Owner: -



-- Name: analytics_audit_log analytics_audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.analytics_audit_log
    ADD CONSTRAINT analytics_audit_log_pkey PRIMARY KEY (id);


-- Name: analytics_cursors analytics_cursors_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.analytics_cursors
    ADD CONSTRAINT analytics_cursors_pkey PRIMARY KEY (seller_id, advertiser_id, storage_key, campaign_id);


-- Name: analytics_records analytics_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.analytics_records
    ADD CONSTRAINT analytics_records_pkey PRIMARY KEY (id);


-- Name: analytics_shop_timezones analytics_shop_timezones_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.analytics_shop_timezones
    ADD CONSTRAINT analytics_shop_timezones_pkey PRIMARY KEY (seller_id);


-- Name: api_keys api_keys_key_hash_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_key_hash_key UNIQUE (key_hash);


-- Name: api_keys api_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);


-- Name: cancellations cancellations_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.cancellations
    ADD CONSTRAINT cancellations_pkey PRIMARY KEY (cancel_id);


-- Name: logistics_sync_targets logistics_sync_targets_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.logistics_sync_targets
    ADD CONSTRAINT logistics_sync_targets_pkey PRIMARY KEY (order_id);


-- Name: logistics_tracking_events logistics_tracking_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.logistics_tracking_events
    ADD CONSTRAINT logistics_tracking_events_pkey PRIMARY KEY (order_id, action_code, event_time);


-- Name: logistics_tracking logistics_tracking_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.logistics_tracking
    ADD CONSTRAINT logistics_tracking_pkey PRIMARY KEY (order_id);


-- Name: miaoshou_collect_box_details miaoshou_collect_box_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.miaoshou_collect_box_details
    ADD CONSTRAINT miaoshou_collect_box_details_pkey PRIMARY KEY (platform, common_collect_box_detail_id);


-- Name: miaoshou_move_collect_tasks miaoshou_move_collect_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.miaoshou_move_collect_tasks
    ADD CONSTRAINT miaoshou_move_collect_tasks_pkey PRIMARY KEY (platform, move_collect_task_detail_id);


-- Name: miaoshou_price_templates miaoshou_price_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.miaoshou_price_templates
    ADD CONSTRAINT miaoshou_price_templates_pkey PRIMARY KEY (price_template_id);


-- Name: miaoshou_shops miaoshou_shops_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.miaoshou_shops
    ADD CONSTRAINT miaoshou_shops_pkey PRIMARY KEY (platform, site, shop_id);


-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (order_id, item_id);


-- Name: order_shippings order_shippings_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.order_shippings
    ADD CONSTRAINT order_shippings_pkey PRIMARY KEY (order_id);


-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (order_id);


-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (payment_id);


-- Name: analytics_daily_completeness pk_analytics_daily_completeness; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.analytics_daily_completeness
    ADD CONSTRAINT pk_analytics_daily_completeness PRIMARY KEY (seller_id, advertiser_id, storage_key, campaign_id, day);


-- Name: analytics_daily_pages pk_analytics_daily_pages; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.analytics_daily_pages
    ADD CONSTRAINT pk_analytics_daily_pages PRIMARY KEY (seller_id, advertiser_id, storage_key, campaign_id, day, page);


-- Name: returns returns_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.returns
    ADD CONSTRAINT returns_pkey PRIMARY KEY (return_id);


-- Name: shops shops_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.shops
    ADD CONSTRAINT shops_pkey PRIMARY KEY (shop_id);


-- Name: statement_transactions statement_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.statement_transactions
    ADD CONSTRAINT statement_transactions_pkey PRIMARY KEY (txn_id);


-- Name: statements statements_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.statements
    ADD CONSTRAINT statements_pkey PRIMARY KEY (statement_id);


-- Name: sync_log sync_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.sync_log
    ADD CONSTRAINT sync_log_pkey PRIMARY KEY (id);


-- Name: analytics_records uq_analytics_records_idem; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.analytics_records
    ADD CONSTRAINT uq_analytics_records_idem UNIQUE (idempotency_key);


-- Name: api_keys uq_api_keys_prefix; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.api_keys
    ADD CONSTRAINT uq_api_keys_prefix UNIQUE (key_prefix);


-- Name: idx_analytics_audit_created; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_analytics_audit_created ON public.analytics_audit_log USING btree (created_at DESC);


-- Name: idx_analytics_audit_request; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_analytics_audit_request ON public.analytics_audit_log USING btree (request_id);


-- Name: idx_analytics_daily_completeness_unit_complete; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_analytics_daily_completeness_unit_complete ON public.analytics_daily_completeness USING btree (seller_id, advertiser_id, storage_key, campaign_id, day, is_complete);


-- Name: idx_analytics_daily_pages_unit; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_analytics_daily_pages_unit ON public.analytics_daily_pages USING btree (seller_id, advertiser_id, storage_key, campaign_id, day);


-- Name: idx_analytics_records_received; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_analytics_records_received ON public.analytics_records USING btree (received_at DESC);


-- Name: idx_analytics_records_request; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_analytics_records_request ON public.analytics_records USING btree (request_id);


-- Name: idx_analytics_records_scope; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_analytics_records_scope ON public.analytics_records USING btree (seller_id, advertiser_id, storage_key, campaign_id, day);


-- Name: idx_analytics_records_scope_page; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_analytics_records_scope_page ON public.analytics_records USING btree (seller_id, advertiser_id, storage_key, campaign_id, day, page);


-- Name: idx_cancellations_create_time; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_cancellations_create_time ON public.cancellations USING btree (create_time DESC);


-- Name: idx_cancellations_order; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_cancellations_order ON public.cancellations USING btree (order_id);


-- Name: idx_cancellations_shop; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_cancellations_shop ON public.cancellations USING btree (shop_id);


-- Name: idx_cancellations_status; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_cancellations_status ON public.cancellations USING btree (cancel_status);


-- Name: idx_logistics_tracking_final_status; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_logistics_tracking_final_status ON public.logistics_tracking USING btree (final_status);


-- Name: idx_logistics_tracking_last_event; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_logistics_tracking_last_event ON public.logistics_tracking USING btree (last_event_at DESC);


-- Name: idx_logistics_tracking_overseas; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_logistics_tracking_overseas ON public.logistics_tracking USING btree (arrived_overseas) WHERE arrived_overseas;


-- Name: idx_logistics_tracking_shop; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_logistics_tracking_shop ON public.logistics_tracking USING btree (shop_id);


-- Name: idx_logistics_tracking_tracking_number; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_logistics_tracking_tracking_number ON public.logistics_tracking USING btree (tracking_number);


-- Name: idx_lt_events_action; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_lt_events_action ON public.logistics_tracking_events USING btree (action_code);


-- Name: idx_lt_events_time; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_lt_events_time ON public.logistics_tracking_events USING btree (event_time DESC);


-- Name: idx_lt_targets_resync; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_lt_targets_resync ON public.logistics_sync_targets USING btree (needs_resync) WHERE (needs_resync = true);


-- Name: idx_lt_targets_shop; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_lt_targets_shop ON public.logistics_sync_targets USING btree (shop_id);


-- Name: idx_miaoshou_collect_box_platform_status; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_miaoshou_collect_box_platform_status ON public.miaoshou_collect_box_details USING btree (platform, status);


-- Name: idx_miaoshou_move_collect_status; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_miaoshou_move_collect_status ON public.miaoshou_move_collect_tasks USING btree (platform, status);


-- Name: idx_miaoshou_move_collect_synced; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_miaoshou_move_collect_synced ON public.miaoshou_move_collect_tasks USING btree (synced_at DESC);


-- Name: idx_miaoshou_shops_platform_site; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_miaoshou_shops_platform_site ON public.miaoshou_shops USING btree (platform, site);


-- Name: idx_miaoshou_shops_synced_at; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_miaoshou_shops_synced_at ON public.miaoshou_shops USING btree (synced_at DESC);


-- Name: idx_order_items_shop; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_order_items_shop ON public.order_items USING btree (shop_id);


-- Name: idx_order_shippings_tracking; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_order_shippings_tracking ON public.order_shippings USING btree (shop_id, order_id) WHERE ((tracking_number IS NOT NULL) AND (tracking_number <> ''::text));


-- Name: idx_orders_create_time; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_orders_create_time ON public.orders USING btree (create_time DESC);


-- Name: idx_orders_shop; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_orders_shop ON public.orders USING btree (shop_id);


-- Name: idx_orders_shop_ct; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_orders_shop_ct ON public.orders USING btree (shop_id, create_time DESC, order_id DESC);


-- Name: idx_orders_status; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders USING btree (order_status_name);


-- Name: idx_payments_paid_time; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_payments_paid_time ON public.payments USING btree (paid_time DESC);


-- Name: idx_payments_shop; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_payments_shop ON public.payments USING btree (shop_id);


-- Name: idx_payments_status; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_payments_status ON public.payments USING btree (status);


-- Name: idx_returns_create_time; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_returns_create_time ON public.returns USING btree (create_time DESC);


-- Name: idx_returns_order; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_returns_order ON public.returns USING btree (order_id);


-- Name: idx_returns_shop; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_returns_shop ON public.returns USING btree (shop_id);


-- Name: idx_returns_status; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_returns_status ON public.returns USING btree (return_status);


-- Name: idx_statements_payment_id; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_statements_payment_id ON public.statements USING btree (payment_id);


-- Name: idx_statements_shop; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_statements_shop ON public.statements USING btree (shop_id);


-- Name: idx_statements_stime; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_statements_stime ON public.statements USING btree (statement_time DESC);


-- Name: idx_stmt_txns_order; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_stmt_txns_order ON public.statement_transactions USING btree (order_id);


-- Name: idx_stmt_txns_shop; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_stmt_txns_shop ON public.statement_transactions USING btree (shop_id);


-- Name: idx_stmt_txns_stmt; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_stmt_txns_stmt ON public.statement_transactions USING btree (statement_id);


-- Name: idx_stmt_txns_type; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_stmt_txns_type ON public.statement_transactions USING btree (type);


-- Name: idx_sync_log_shop; Type: INDEX; Schema: public; Owner: -

CREATE INDEX IF NOT EXISTS idx_sync_log_shop ON public.sync_log USING btree (shop_id, started_at DESC);


-- Name: orders trg_orders_touch; Type: TRIGGER; Schema: public; Owner: -

CREATE OR REPLACE TRIGGER trg_orders_touch BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();


-- Name: shops trg_shops_touch; Type: TRIGGER; Schema: public; Owner: -

CREATE OR REPLACE TRIGGER trg_shops_touch BEFORE UPDATE ON public.shops FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();


-- Name: sync_log trg_sync_log_retention; Type: TRIGGER; Schema: public; Owner: -

CREATE OR REPLACE TRIGGER trg_sync_log_retention AFTER INSERT ON public.sync_log FOR EACH STATEMENT EXECUTE FUNCTION public.trg_sync_log_retention_fn();


-- PostgreSQL database dump complete

\unrestrict ZGHgNvf16OmDGU9JEoH59Kc1xOFSehZY2GoUUQd4QjxfinPmeKaQD9kna92bbAE

