"""Constrained ADB adapter; no arbitrary shell command is exposed."""

from __future__ import annotations

import asyncio
from pathlib import Path


class DeviceUnavailable(RuntimeError):
    pass


class DeviceLocked(DeviceUnavailable):
    pass


class AdbDevice:
    def __init__(self, adb_binary: str = "adb", *, album: str = "TTSERP") -> None:
        self.adb_binary = adb_binary
        self.album = album

    async def _run(self, *args: str, timeout: float = 30) -> str:
        process = await asyncio.create_subprocess_exec(
            self.adb_binary,
            *args,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(process.communicate(), timeout=timeout)
        if process.returncode:
            raise DeviceUnavailable(stderr.decode(errors="replace").strip()[:500])
        return stdout.decode(errors="replace")

    async def check_device(self, serial: str) -> None:
        output = await self._run("-s", serial, "get-state")
        if output.strip() != "device":
            raise DeviceUnavailable("目标设备未在线")

    async def check_package(self, serial: str, package: str) -> None:
        output = await self._run("-s", serial, "shell", "pm", "path", package)
        if "package:" not in output:
            raise DeviceUnavailable("TikTok 未安装")

    async def stage_video(
        self, serial: str, local_path: Path, device_path: str
    ) -> None:
        await self._run("-s", serial, "shell", "mkdir", "-p", "/sdcard/Movies/TTSERP")
        await self._run("-s", serial, "push", str(local_path), device_path, timeout=180)
        size = await self._run("-s", serial, "shell", "stat", "-c", "%s", device_path)
        if int(size.strip() or "-1") != local_path.stat().st_size:
            raise DeviceUnavailable("设备视频大小校验失败")
        # am broadcast is a fixed command with a server-generated path.
        await self._run(
            "-s",
            serial,
            "shell",
            "am",
            "broadcast",
            "-a",
            "android.intent.action.MEDIA_SCANNER_SCAN_FILE",
            "-d",
            f"file://{device_path}",
        )

    async def verify_media_visible(self, serial: str, device_path: str) -> None:
        output = await self._run(
            "-s",
            serial,
            "shell",
            "content",
            "query",
            "--uri",
            "content://media/external/file",
            "--projection",
            "_data",
        )
        if device_path not in output:
            raise DeviceUnavailable("视频尚未出现在 TTSERP 相册")

    async def remove_staged_video(self, serial: str, device_path: str) -> None:
        # The path is generated by ttsERP and constrained to its own album.
        if not device_path.startswith("/sdcard/Movies/TTSERP/tts_erp_"):
            raise ValueError("refusing to remove an unmanaged device path")
        await self._run("-s", serial, "shell", "rm", "-f", device_path)
